name: Push to dockerhub

on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup docker
          uses: docker/setup-buildx-action@v3
        
        - name: Build docker image
          run: docker build -f Dockerfile.docs -t sarthaksbiswas29/gdocs-fe:${{ github.sha }} .
        
        - name: Login to dockerhub
          run: docker login -u sarthaksbiswas29 -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: Push docker image
          run: docker push sarthaksbiswas29/gdocs-fe:${{ github.sha }}

